<?php

namespace UMSdk\Service;

use Illuminate\Support\ServiceProvider;
use UMSdk\UMPushAndroid;
use UMSdk\UMPushIOS;

class DumpServiceProvider extends ServiceProvider
{

    public function boot(): void
    {
        //发布配置文件到项目的 config 目录中
        $this->publishes([
            __DIR__ . '/../../config/push.php' => config_path('push.php'),
        ], 'config');
    }

    public function register()
    {
        //        parent::register(); // TODO: Change the autogenerated stub
        $this->mergeConfigFrom(__DIR__ . '/../../config/push.php', 'push');
        $this->app->singleton('push.ios', function ($app)
        {
            return new UMPushIOS($app['config']);
        });
        $this->app->singleton('push.android', function ($app)
        {
            return new UMPushAndroid($app['config']);
        });
    }

    public function provides()
    {
        // 因为延迟加载 所以要定义 provides 函数 具体参考laravel 文档
        return ['push.ios','push.android'];
    }
}