<?php


namespace UMSdk\Facade;


use Illuminate\Support\Facades\Facade;
use UMSdk\Config\IosPushBody;

/**
 * @method static void sendIOSUnicast(IosPushBody $body)
 * @method static void sendIOSBroadcast(IosPushBody $body)
 * @see \UMSdk\UMPushIOS
 *
 * Class UMPushIOS
 * @package UMSdk\Facade
 */
class UMPushIos extends Facade
{
    protected static function getFacadeAccessor()
    {
        //    parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
        return "push.ios";
    }
}